/*
 * This source file was generated by the Gradle 'init' task
 */
package book;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.bookstore.books.*;
import com.bookstore.customer.Customer;
import java.math.BigDecimal;

class AppTest {
    @Test void bookstoreClassesExist() {
        // Test that we can create book instances
        PhysicalBook physicalBook = new PhysicalBook("123", "Test Book", "Test Author", new BigDecimal("10.00"));
        assertNotNull(physicalBook, "PhysicalBook should be created");
        assertEquals("Test Book", physicalBook.getTitle(), "Book title should match");
        
        EBook ebook = new EBook("456", "Test EBook", "Test Author", new BigDecimal("10.00"));
        assertNotNull(ebook, "EBook should be created");
        assertTrue(ebook.calculatePrice().compareTo(new BigDecimal("9.00")) == 0, "EBook should have 10% discount");
        
        AudioBook audiobook = new AudioBook("789", "Test AudioBook", "Test Author", new BigDecimal("10.00"));
        assertNotNull(audiobook, "AudioBook should be created");
        assertTrue(audiobook.calculatePrice().compareTo(new BigDecimal("10.50")) == 0, "AudioBook should have 5% fee");
        
        Customer customer = new Customer("C001", "Test User", Customer.CustomerType.GENERAL);
        assertNotNull(customer, "Customer should be created");
        assertFalse(customer.isVIP(), "General customer should not be VIP");
    }
}
